all: serveur1 serveur2 serveur3

serveur1: 
	go build serveur1-LesTryhardeusesDuDimanche.go

serveur2:
	go build serveur2-LesTryhardeusesDuDimanche.go

serveur3:
	go build serveur3-LesTryhardeusesDuDimanche.go

clean: 
	rm serveur1-LesTryhardeusesDuDimanche.go
	rm serveur2-LesTryhardeusesDuDimanche.go
	rm serveur3-LesTryhardeusesDuDimanche.go
	go clean


